export const GET_DATA_REQUESTED = 'GET_DATA_REQUESTED';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILED = 'GET_DATA_FAILED';

export const FILTER_CONDITION_REQUEST = 'FILTER_CONDITION_REQUEST';
export const FILTER_CONDITION_SUCCESS = 'FILTER_BY_SUCCESS';
export const FILTER_CONDITION_ERROR = 'FILTER_BY_ERROR';

export const ADD_DATA_REQUESTED = 'ADD_DATA_REQUESTED';
export const ADD_DATA_SUCCESS = 'ADD_DATA_SUCCESS';
export const ADD_DATA_ERROR = 'ADD_DATA_ERROR';